version: '3'
services:
 web:
  image: rabbitmq:3-management
  container_name: rabbit_web
  ports:
   - "15672:15672"
  links:
   - rabbit-client

 rabbit-client:
  image: minteemer/rabbit-client
  container_name: rabbit_client
  build: .